name: opensfm
dependencies:
    - python=3.10
    - cmake=3.31
    - make
    - libxcrypt
    - libopencv *=headless*
    - py-opencv
    - anaconda::ceres-solver=2.2
    - conda-forge::llvm-openmp
    - conda-forge::cxx-compiler
    - anaconda::suitesparse
    - conda-forge::openblas
    - anaconda::metis