name: opensfm
dependencies:
    - python=3.10
    - cmake=3.31
    - make
    - libxcrypt
    - libopencv *=headless*
    - py-opencv
    - conda-forge::libvorbis
    - ceres-solver=2.1
    - conda-forge::llvm-openmp
    - conda-forge::cxx-compiler
