# Autogenerated by pybind stub generator
# Do not manually edit
# To regenerate:
#   $ buck run //mapillary/opensfm/opensfm/src/robust:pyrobust_stubgen
# @generated
#
# Tip: Be sure to run this with the build mode you use for your project, e.g.,
# @//arvr/mode/linux/opt (or dev) in arvr.
#
# Ignore errors for [24] untyped generics.
# pyre-ignore-all-errors[24]

from __future__ import annotations

import collections.abc
import typing

import numpy

__all__: list[str] = [
    "LMedS",
    "MSAC",
    "RANSAC",
    "RansacType",
    "RobustEstimatorParams",
    "ScoreInfoLine",
    "ScoreInfoMatrix34d",
    "ScoreInfoMatrix3d",
    "ScoreInfoMatrix4d",
    "ScoreInfoVector3d",
    "ransac_absolute_pose",
    "ransac_absolute_pose_known_rotation",
    "ransac_essential",
    "ransac_line",
    "ransac_relative_pose",
    "ransac_relative_rotation",
    "ransac_similarity",
]

class RansacType:
    LMedS: typing.ClassVar[RansacType]  # value = <RansacType.LMedS: 2>
    MSAC: typing.ClassVar[RansacType]  # value = <RansacType.MSAC: 1>
    RANSAC: typing.ClassVar[RansacType]  # value = <RansacType.RANSAC: 0>
    __members__: typing.ClassVar[
        dict[str, RansacType]
    ]  # value = {'RANSAC': <RansacType.RANSAC: 0>, 'MSAC': <RansacType.MSAC: 1>, 'LMedS': <RansacType.LMedS: 2>}
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(
        self, state: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RobustEstimatorParams:
    use_iteration_reduction: bool
    use_local_optimization: bool
    def __init__(self) -> None: ...
    @property
    def iterations(self) -> int: ...
    @iterations.setter
    def iterations(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def probability(self) -> float: ...
    @probability.setter
    def probability(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...

class ScoreInfoLine:
    def __init__(self) -> None: ...
    @property
    def inliers_indices(self) -> list[int]: ...
    @inliers_indices.setter
    def inliers_indices(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def lo_model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]: ...
    @lo_model.setter
    def lo_model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]
    ) -> None: ...
    @property
    def model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]: ...
    @model.setter
    def model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]
    ) -> None: ...
    @property
    def score(self) -> float: ...
    @score.setter
    def score(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class ScoreInfoMatrix34d:
    def __init__(self) -> None: ...
    @property
    def inliers_indices(self) -> list[int]: ...
    @inliers_indices.setter
    def inliers_indices(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def lo_model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 4]"]: ...
    @lo_model.setter
    def lo_model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 4]"]
    ) -> None: ...
    @property
    def model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 4]"]: ...
    @model.setter
    def model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 4]"]
    ) -> None: ...
    @property
    def score(self) -> float: ...
    @score.setter
    def score(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class ScoreInfoMatrix3d:
    def __init__(self) -> None: ...
    @property
    def inliers_indices(self) -> list[int]: ...
    @inliers_indices.setter
    def inliers_indices(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def lo_model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]: ...
    @lo_model.setter
    def lo_model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]
    ) -> None: ...
    @property
    def model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]: ...
    @model.setter
    def model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]
    ) -> None: ...
    @property
    def score(self) -> float: ...
    @score.setter
    def score(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class ScoreInfoMatrix4d:
    def __init__(self) -> None: ...
    @property
    def inliers_indices(self) -> list[int]: ...
    @inliers_indices.setter
    def inliers_indices(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def lo_model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]: ...
    @lo_model.setter
    def lo_model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]
    ) -> None: ...
    @property
    def model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]: ...
    @model.setter
    def model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]
    ) -> None: ...
    @property
    def score(self) -> float: ...
    @score.setter
    def score(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class ScoreInfoVector3d:
    def __init__(self) -> None: ...
    @property
    def inliers_indices(self) -> list[int]: ...
    @inliers_indices.setter
    def inliers_indices(
        self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]
    ) -> None: ...
    @property
    def lo_model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @lo_model.setter
    def lo_model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> None: ...
    @property
    def model(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @model.setter
    def model(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> None: ...
    @property
    def score(self) -> float: ...
    @score.setter
    def score(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

def ransac_absolute_pose(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: RobustEstimatorParams,
    arg4: RansacType,
) -> ScoreInfoMatrix34d: ...
def ransac_absolute_pose_known_rotation(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: RobustEstimatorParams,
    arg4: RansacType,
) -> ScoreInfoVector3d: ...
def ransac_essential(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: RobustEstimatorParams,
    arg4: RansacType,
) -> ScoreInfoMatrix3d: ...
def ransac_line(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"],
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: RobustEstimatorParams,
    arg3: RansacType,
) -> ScoreInfoLine: ...
def ransac_relative_pose(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: RobustEstimatorParams,
    arg4: RansacType,
) -> ScoreInfoMatrix34d: ...
def ransac_relative_rotation(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: RobustEstimatorParams,
    arg4: RansacType,
) -> ScoreInfoMatrix3d: ...
def ransac_similarity(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"],
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: RobustEstimatorParams,
    arg4: RansacType,
) -> ScoreInfoMatrix4d: ...

LMedS: RansacType  # value = <RansacType.LMedS: 2>
MSAC: RansacType  # value = <RansacType.MSAC: 1>
RANSAC: RansacType  # value = <RansacType.RANSAC: 0>
