from typing import List, Tuple, Dict, Set, Any
from opensfm.pybundle import BundleAdjuster
from opensfm.pymap import Shot, TracksManager, RigCamera, Map
from opensfm.pygeometry import Camera

import numpy


class BAHelpers:
    @staticmethod
    def bundle(arg0, arg1: Dict[str, Camera], arg2: Dict[str, RigCamera], arg3, arg4: dict) -> dict: ...
    @staticmethod
    def bundle_local(arg0, arg1: Dict[str, Camera], arg2: Dict[str, RigCamera], arg2, arg3: str, arg4: dict) -> tuple: ...
    @staticmethod
    def bundle_shot_poses(arg0, arg1: Set[str], arg2: Dict[str, Camera], arg3: Dict[str, RigCamera], arg4: dict) -> dict: ...
    @staticmethod
    def bundle_to_map(arg0: BundleAdjuster, arg1: Map, arg3: bool) -> None: ...
    @staticmethod
    def detect_alignment_constraints(arg0: dict, arg1) -> str: ...
    @staticmethod
    def shot_neighborhood_ids(arg0: str, arg1: int, arg2: int, arg3: int) -> Tuple[Set[str],Set[str]]: ...

def count_tracks_per_shot(arg0: TracksManager, arg1: List[str], arg2: List[str]) -> Dict[str,int]: ...
def add_connections(arg0: TracksManager, arg1: str, arg2: List[Tuple[int, str]]) -> None: ...
def remove_connections(arg0: TracksManager, arg1: str, arg2: List[Tuple[int, str]]) -> None: ...
def realign_points(arg0: Map, arg2: Map) -> Any: ...
