# Autogenerated by pybind stub generator
# Do not manually edit
# To regenerate:
#   $ buck run //mapillary/opensfm/opensfm/src/features:pyfeatures_stubgen
# @generated
#
# Tip: Be sure to run this with the build mode you use for your project, e.g.,
# @//arvr/mode/linux/opt (or dev) in arvr.
#
# Ignore errors for [24] untyped generics.
# pyre-ignore-all-errors[24]

from __future__ import annotations

import collections.abc
import typing

import numpy

__all__: list[str] = [
    "AKAZEOptions",
    "AkazeDescriptorType",
    "AkazeDiffusivityType",
    "akaze",
    "compute_vlad_descriptor",
    "compute_vlad_distances",
    "hahog",
    "match_using_words",
]

class AKAZEOptions:
    descriptor: AkazeDescriptorType
    diffusivity: AkazeDiffusivityType
    save_keypoints: bool
    save_scale_space: bool
    use_adaptive_suppression: bool
    use_isotropic_diffusion: bool
    verbosity: bool
    def __init__(self) -> None: ...
    @property
    def derivative_factor(self) -> float: ...
    @derivative_factor.setter
    def derivative_factor(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...
    @property
    def descriptor_channels(self) -> int: ...
    @descriptor_channels.setter
    def descriptor_channels(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def descriptor_pattern_size(self) -> int: ...
    @descriptor_pattern_size.setter
    def descriptor_pattern_size(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def descriptor_size(self) -> int: ...
    @descriptor_size.setter
    def descriptor_size(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def dthreshold(self) -> float: ...
    @dthreshold.setter
    def dthreshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def img_height(self) -> int: ...
    @img_height.setter
    def img_height(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def img_width(self) -> int: ...
    @img_width.setter
    def img_width(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def kcontrast(self) -> float: ...
    @kcontrast.setter
    def kcontrast(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def kcontrast_nbins(self) -> int: ...
    @kcontrast_nbins.setter
    def kcontrast_nbins(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def kcontrast_percentile(self) -> float: ...
    @kcontrast_percentile.setter
    def kcontrast_percentile(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...
    @property
    def min_dthreshold(self) -> float: ...
    @min_dthreshold.setter
    def min_dthreshold(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...
    @property
    def nsublevels(self) -> int: ...
    @nsublevels.setter
    def nsublevels(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def omax(self) -> int: ...
    @omax.setter
    def omax(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def omin(self) -> int: ...
    @omin.setter
    def omin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def sderivatives(self) -> float: ...
    @sderivatives.setter
    def sderivatives(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...
    @property
    def soffset(self) -> float: ...
    @soffset.setter
    def soffset(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def target_num_features(self) -> int: ...
    @target_num_features.setter
    def target_num_features(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...

class AkazeDescriptorType:
    MLDB: typing.ClassVar[AkazeDescriptorType]  # value = <AkazeDescriptorType.MLDB: 5>
    MLDB_UPRIGHT: typing.ClassVar[
        AkazeDescriptorType
    ]  # value = <AkazeDescriptorType.MLDB_UPRIGHT: 4>
    MSURF: typing.ClassVar[
        AkazeDescriptorType
    ]  # value = <AkazeDescriptorType.MSURF: 3>
    MSURF_UPRIGHT: typing.ClassVar[
        AkazeDescriptorType
    ]  # value = <AkazeDescriptorType.MSURF_UPRIGHT: 2>
    SURF: typing.ClassVar[AkazeDescriptorType]  # value = <AkazeDescriptorType.SURF: 1>
    SURF_UPRIGHT: typing.ClassVar[
        AkazeDescriptorType
    ]  # value = <AkazeDescriptorType.SURF_UPRIGHT: 0>
    __members__: typing.ClassVar[
        dict[str, AkazeDescriptorType]
    ]  # value = {'SURF_UPRIGHT': <AkazeDescriptorType.SURF_UPRIGHT: 0>, 'SURF': <AkazeDescriptorType.SURF: 1>, 'MSURF_UPRIGHT': <AkazeDescriptorType.MSURF_UPRIGHT: 2>, 'MSURF': <AkazeDescriptorType.MSURF: 3>, 'MLDB_UPRIGHT': <AkazeDescriptorType.MLDB_UPRIGHT: 4>, 'MLDB': <AkazeDescriptorType.MLDB: 5>}
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(
        self, state: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class AkazeDiffusivityType:
    CHARBONNIER: typing.ClassVar[
        AkazeDiffusivityType
    ]  # value = <AkazeDiffusivityType.CHARBONNIER: 3>
    PM_G1: typing.ClassVar[
        AkazeDiffusivityType
    ]  # value = <AkazeDiffusivityType.PM_G1: 0>
    PM_G2: typing.ClassVar[
        AkazeDiffusivityType
    ]  # value = <AkazeDiffusivityType.PM_G2: 1>
    WEICKERT: typing.ClassVar[
        AkazeDiffusivityType
    ]  # value = <AkazeDiffusivityType.WEICKERT: 2>
    __members__: typing.ClassVar[
        dict[str, AkazeDiffusivityType]
    ]  # value = {'PM_G1': <AkazeDiffusivityType.PM_G1: 0>, 'PM_G2': <AkazeDiffusivityType.PM_G2: 1>, 'WEICKERT': <AkazeDiffusivityType.WEICKERT: 2>, 'CHARBONNIER': <AkazeDiffusivityType.CHARBONNIER: 3>}
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(
        self, state: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def akaze(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: AKAZEOptions
) -> tuple: ...
def compute_vlad_descriptor(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]: ...
def compute_vlad_distances(
    arg0: collections.abc.Mapping[
        str, typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]
    ],
    arg1: str,
    arg2: collections.abc.Set[str],
) -> tuple[list[float], list[str]]: ...
def hahog(
    image: typing.Annotated[numpy.typing.ArrayLike, numpy.float32],
    peak_threshold: typing.SupportsFloat | typing.SupportsIndex = 0.003,
    edge_threshold: typing.SupportsFloat | typing.SupportsIndex = 10,
    target_num_features: typing.SupportsInt | typing.SupportsIndex = 0,
) -> tuple: ...
def match_using_words(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32],
    arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    arg4: typing.SupportsFloat | typing.SupportsIndex,
    arg5: typing.SupportsInt | typing.SupportsIndex,
) -> numpy.typing.NDArray[numpy.int32]: ...
