# Autogenerated by pybind stub generator
# Do not manually edit
# To regenerate:
#   $ buck run //mapillary/opensfm/opensfm/src/geo:pygeo_stubgen
# @generated
#
# Tip: Be sure to run this with the build mode you use for your project, e.g.,
# @//arvr/mode/linux/opt (or dev) in arvr.
#
# Ignore errors for [24] untyped generics.
# pyre-ignore-all-errors[24]

from __future__ import annotations

import typing

import numpy

__all__: list[str] = [
    "TopocentricConverter",
    "ecef_from_lla",
    "ecef_from_topocentric_transform",
    "ecef_from_topocentric_transform_finite_diff",
    "gps_distance",
    "lla_from_ecef",
    "lla_from_topocentric",
    "topocentric_from_lla",
]

class TopocentricConverter:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: typing.SupportsFloat | typing.SupportsIndex,
        arg1: typing.SupportsFloat | typing.SupportsIndex,
        arg2: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...
    @property
    def alt(self) -> float: ...
    @property
    def lat(self) -> float: ...
    @property
    def lon(self) -> float: ...

@typing.overload
def ecef_from_lla(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def ecef_from_lla(
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def ecef_from_topocentric_transform(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]: ...
@typing.overload
def ecef_from_topocentric_transform(
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]: ...
@typing.overload
def ecef_from_topocentric_transform_finite_diff(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]: ...
@typing.overload
def ecef_from_topocentric_transform_finite_diff(
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]: ...
def gps_distance(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"],
) -> float: ...
@typing.overload
def lla_from_ecef(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def lla_from_ecef(
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def lla_from_topocentric(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def lla_from_topocentric(
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: typing.SupportsFloat | typing.SupportsIndex,
    arg4: typing.SupportsFloat | typing.SupportsIndex,
    arg5: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def topocentric_from_lla(
    arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@typing.overload
def topocentric_from_lla(
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: typing.SupportsFloat | typing.SupportsIndex,
    arg4: typing.SupportsFloat | typing.SupportsIndex,
    arg5: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
